return {
	-- "AckslD/nvim-neoclip.lua",
	-- dependencies = {
	-- 	{ "nvim-telescope/telescope.nvim" },
	-- 	{ "kkharji/sqlite.lua", module = "sqlite" },
	-- },
	-- config = function()
	-- 	require("neoclip").setup({
	-- 		history = 1000,
	-- 		enable_persistent_history = true,
	-- 		length_limit = 1048576,
	-- 		continuous_sync = true,
	-- 		db_path = vim.fn.stdpath("data") .. "/databases/neoclip.sqlite3",
	-- 		filter = nil,
	-- 		preview = true,
	-- 		prompt = nil,
	-- 		default_register = '"',
	-- 		default_register_macros = "q",
	-- 		enable_macro_history = true,
	-- 		content_spec_column = false,
	-- 		disable_keycodes_parsing = false,
	-- 	})
	-- end,
}
