[MainWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x1b\0\0\0\x1c\0\0\x3Z\0\0\x4*\0\0\0\x1e\0\0\0\x1f\0\0\x3W\0\0\x4'\0\0\0\0\0\0\0\0\a\x80\0\0\0\x1e\0\0\0\x1f\0\0\x3W\0\0\x4')

[Settings]
checkRcloneBrowserUpdates=true
checkRcloneUpdates=true
darkMode=false
darkModeIni=false
defaultDownloadOptions=
defaultRcloneOptions=--fast-list
defaultUploadOptions=
driveShared=0
http_proxy=
https_proxy=
iconSize=medium
lastRcloneBrowserUpdateCheck=Thu Aug 22 2024
lastRcloneUpdateCheck=Thu Aug 22 2024
lastUsedDestFolder=/home/fitsum/Documents/rclone
lastUsedSourceFolder=/home/fitsum/Documents/rclone
no_proxy=
rclone=/usr/bin/rclone
rcloneVersion=1.67.0
useProxy=false
