font_size 12.0
window_padding_width 25
include theme.conf
background_opacity 0.60
hide_window_decorations yes
confirm_os_window_close 0

# BEGIN_KITTY_FONTS
font_family      family="CaskaydiaCove Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
dynamic_background_opacity yes
map alt+a  set_background_opacity +0.1
map alt+s  set_background_opacity -0.1

map alt+shift+k change_font_size all +2.0 
map alt+shift+j  change_font_size all -2.0 
map alt+shift+backspace change_font_size all 0

map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
map alt+k scroll_page_up
map alt+j scroll_page_down

map ctrl+w no_op
map ctrl+shift+t no_op
map ctrl+shift+w no_op
map ctrl+shift+u no_op
map ctrl+shift+e no_op
map ctrl+shift+h no_op


